### PR TITLE
perform indefinite background reconnection attempts

### LINKED ISSUE #18: agent-connection: asynchronously attempt to dial and retry
Currently the logic is a best case exponential backoff scheme that fails fast if the agent cannot be reached. However, this makes is hard for applications on environments that need to configure the agent later than the applications have been deployed.

In the case that the agent connection cannot be made, converted spans should be dropped or perhaps collected for some period of time or in a buffer but will be a noop to send.

This makes it very easy for cloud providers and internal deployments to start the agent at their own pace, take it down for maintenance, migrate applications to various environments etc but also have a seamless OpenCensus experience.

### PR DESCRIPTION
**Pull request by odeke-em**
Perform an indefinite background redial on failed connections
to ensure that this exporter can reconnect to the upstream
OpenCensus interceptor/agent.

This change allows environments that don't yet have the agent
deployed to start using this exporter and gradually roll-out
the agent. It helps trivial situations like an application
starting before the agent: of which it shouldn't crash
and fail to start running -- all the exported spans before
the agent is ready for connections, or at least if the
span buffer is full, will be discarded.

Added tests to ensure that this works and lock-in that
behavior.

Fixes #18

### CODE REVIEW

**Comment by songy23** [comment]
Please fix the tests. Looks like there're race conditions.

File: connection.go [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+
+func (ae *Exporter) setStateConnected() {
+	atomic.StoreInt32(&ae.connectionState, sConnected)
+}
+
+func (ae *Exporter) connected() bool {
+	return atomic.LoadInt32(&ae.connectionState) == sConnected
+}
+
+const defaultConnReattemptPeriod = 5000 * time.Millisecond
```
Comment (songy23) [inline connection.go]: 5 seconds seems too frequent to me, consider 5 minutes by default instead?

File: ocagent.go [hunk 2]
```diff
@@ -170,32 +186,18 @@ func (ae *Exporter) doStartLocked() error {
...
-	var cc *grpc.ClientConn
-	dialOpts = append(dialOpts, grpc.WithTimeout(1*time.Second))
-	dialBackoffWaitPeriod := 50 * time.Millisecond
-	err := nTriesWithExponentialBackoff(5, dialBackoffWaitPeriod, func() error {
-		var err error
-		cc, err = grpc.Dial(addr, dialOpts...)
-		return err
-	})
-	return cc, err
+	return grpc.Dial(addr, dialOpts...)
```
Comment (songy23) [inline ocagent.go]: I would wish we had something similar in Java :)

File: connection.go (hunk 1 above)
Comment (odeke-em) [reply connection.go]: 5 minutes seems too long though, because even the max grpc exponential backoff delay by default is 2 minutes(120 seconds) https://godoc.org/google.golang.org/grpc#DefaultBackoffConfig but that's after trying for 1 second, about 7 times which basically becomes trying for at least 247 seconds(4.11 minutes) altogether. Perhaps a value in between?

Comment (songy23) [reply connection.go]: One minute may be a good compromise?

Comment (odeke-em) [reply connection.go]: Perfect, I was thinking the same too.

Comment (odeke-em) [reply connection.go]: On second thought, I've looked at the application sitting still for 1 minute, that seems like waaay too long even still. Am looking at perhaps 10 seconds: gRPC-Go by default does a dial for atleast every one of these times:
[1s, 2s, 4s, 8s, 16s, 32s, 64s, 120s] then gives up
putting it at 1 minute would be at the end of that time wait and can result in the loss of many spans.

**Comment by odeke-em** [comment]
Thank you @songy23 for the review!
