### PR TITLE
Ensure exporter respects ResourceDetector option

### LINKED ISSUE #79: Exporter doesn't respect ResourceDetector option
Exporter fails to detect resource when using ResourceDetector option.

Example code:
```
opts := []ocagent.ExporterOption{ocagent.WithServiceName(config.component)}
opts = append(opts, ocagent.WithResourceDetector(func(context.Context) (*resource.Resource, error) {
	return &resource.Resource{Type: "knative_Revision"}, nil
}))
e, err := ocagent.NewExporter(opts...)
```

When I put a debug print out in the code I see the resource type is missing:

`2020/01/18 01:59:29 ExportMetricsServiceRequest called. req: &v1.Resource{Type:", Labels:map[string]string(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:18}
`

### PR DESCRIPTION
**Pull request by anniefu**
When WithResourceDetector option is used, make sure exporter uses ResourceDetector's detected resource when exporting traces and metrics.

Fixes #79

### CODE REVIEW

File: ocagent.go [hunk 1]
```diff
@@ -504,7 +504,7 @@ func (ae *Exporter) uploadTraces(sdl []*trace.SpanData) {
 		ae.senderMu.Lock()
 		err := ae.traceExporter.Send(&agenttracepb.ExportTraceServiceRequest{
 			Spans:    protoSpans,
```
Comment (anniefu) [inline ocagent.go]: I couldn't find an existing test that checks the resource type for exported traces. Any suggestions on how to test this change?

Comment (rghetia) [reply ocagent.go]: you can add resource in addition to span and nodes [here](https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/blob/a8a6f458bbc1d5042322ad1f9b65eeb0b69be9ea/mock_agent_test.go#L128-L129) in  mock_agent_test.go and then modify the test in ocagent_test.go to verify the resources like you have done for metrics.

Comment (anniefu) [reply ocagent.go]: Thanks! I've added a test for checking the resource type on the exported traces.
